### ISSUE TITLE
How to change online da to sfda setting?

### ISSUE THREAD

**Issue by HuizaiVictorYao** [Vibashan/online-od#4]
Hi there!
It seems that the execution instructions from README.md is only for online-da setting.
I'm new to Detectron2 and I wonder how to modify the instructions or code to run sfda part? thx

**Comment by Vibashan** [comment]
Hi, 

If you are interested in the Source-free part, please look into our recent CVPR codebase [IRG](https://github.com/Vibashan/irg-sfda).

Our source-free codebase is also built on top of Detectron codebase.

**Comment by HuizaiVictorYao** [comment]
I've read both your CVPR and WACV papers and your novel thoughts have brought me huge inspirations. 

But it seems that the two sfda methods are different and the experiment results of sfda parts are also different. I have also run both codes and tried to modify yaml and train.py of WACV codebase to reproduce sfda part, but it doesn't work. 

I'm still confused about how you conduct the source free experiments in this paper and how I can reproduce them. Would you please show me in detail?

**Comment by Vibashan** [comment]
Hi @VictorYrotciV ,

For evaluation purposes and fair comparision, for online we reported the results after 1 epoch and for offline we reported the results after 10 epochs.

**Comment by HuizaiVictorYao** [comment]
> Hi @VictorYrotciV ,
> 
> For evaluation purposes and fair comparision, for online we reported the results after 1 epoch and for offline we reported the results after 10 epochs.

I got it. Thanks for your reply!
